_target_: lightning.pytorch.trainer.Trainer

default_root_dir: ${paths.output_dir}

min_epochs: 1 # prevents early stopping
max_epochs: 10

accelerator: cpu
devices: 1

# mixed precision for extra speed-up
# precision: 16

# perform a validation loop every N training epochs
check_val_every_n_epoch: 1

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False

# # Training settings
# time_lags:
#   ligand_receptor: 5
#   receptor_gene: 3
#   ligand_gene: 1

# epochs: 20
# learning_rate: 0.001
# weight_decay: 0.0001
# optimizer: "adam"  # Options: "sgd", "adam"
# scheduler:
#   type: "StepLR"
#   step_size: 5
#   gamma: 0.1
# early_stopping:
#   patience: 5
#   min_delta: 0.001

